spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/./mms
    username: sa
    password:
    driver-class-name: org.h2.Driver

  redis:
    host: localhost
    port: 6379

    properties:
      hibernate:
        show_sql: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
#        default_batch_fetch_size: 1000
    open-in-view: true
#  data:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page-size: 2000
#        one-indexed-parameters: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace